vethelp/places/urls.py
from django.urls import path

from . import views

app_name='places'

urlpatterns = [
    path('', views.show_info, name='info'),
    path('vet_clinics', views.get_clinics, name='clinics'),
    path('vet_clinics/<int:id>', views.get_profile, name='clinic'),
    path('vet_clinics/<int:clinic_id>/comment/', views.add_comment, name='add_comment'),
    path('walking_areas', views.get_areas, name='areas'),
]

vethelp/users/urls.py
from django.contrib.auth.views import LogoutView
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import PasswordResetView
from django.contrib.auth.views import PasswordResetDoneView
from django.contrib.auth.views import PasswordResetConfirmView
from django.contrib.auth.views import PasswordResetCompleteView
from django.contrib.auth.views import PasswordChangeView
from django.contrib.auth.views import PasswordChangeDoneView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path(
        'signup/',
        views.SignUp.as_view(),
        name='signup'
    ),
    path(
        'login/',
        LoginView.as_view(
            template_name='users/login.html'
        ),
        name='login'
    ),
    path(
        'logout/',
        LogoutView.as_view(
            template_name='users/logged_out.html'
        ),
        name='logout'
    ),
    path(
        'password_change/',
        PasswordChangeView.as_view(
            template_name='users/password_change_form.html'
        ),
        name='password_change'
    ),
    path(
        'password_change/done/',
        PasswordChangeDoneView.as_view(
            template_name='users/password_change_done.html'
        ),
        name='password_change_done'
    ),
    path(
        'password_reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset_form.html'
        ),
        name='password_reset'
    ),
    path(
        'password_reset/done/',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'reset/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html'
        ),
        name='password_reset_confirm'
    ),
    path(
        'reset/done/',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),

]

vethelp/vethelp/urls.py
from django.contrib import admin
from django.urls.conf import include
from django.urls import path

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('places.urls', namespace='places'))
]

vethelp/places/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models.fields import SlugField, TextField
from django.db.models.constraints import UniqueConstraint

User = get_user_model()

class Clinic(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Название ветеринарного учреждения'
    )

    class Meta:
        ordering = ('title',)
        verbose_name = 'Ветеринарное учреждение'
        verbose_name_plural = 'Ветеринарные учреждения'

    def __str__(self):
        return self.title


class Comment(models.Model):
    clinic = models.ForeignKey(
        Clinic,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Ветеринарное учреждение',
        help_text="Ветеринарное учреждение, к которому будет относиться комментарий."
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
        help_text="Автор комментария."
    )
    text = models.TextField(verbose_name='Текст комментария')
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата',
        help_text="Дата комментария"
    )

    class Meta:
        ordering = ('-created',)
        verbose_name = u'Комментарий'
        verbose_name_plural = u'Комментарии'

    def __str__(self):
        return self.text

vethelp/places/forms.py
from django.forms import ModelForm

from .models import Comment


class CommentForm(ModelForm):
    class Meta():
        model = Comment
        fields = ('text',)

vethelp/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model


User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

vethelp/core/views.py
from django.shortcuts import render


def page_not_found(request, exception):
    return render(request, 'core/404.html', {'path': request.path}, status=404)


def server_error(request):
    return render(request, 'core/500.html', status=500)


def permission_denied(request, exception):
    return render(request, 'core/403.html', status=403)


def csrf_failure(request, reason=''):
    return render(request, 'core/403csrf.html')

vethelp/places/views.py
from pydoc import cli
from django.core.paginator import Paginator
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib.auth.decorators import login_required

from .forms import CommentForm

from .models import Clinic


def show_info(request):
    return render(request, 'places/info.html')

def get_clinics(request):
    clinics = Clinic.objects.all()
    context = {
        'clinics': clinics
    }
    return render(request, 'places/clinic.html', context)

def get_areas(request):
    return render(request, 'places/area.html')

def get_profile(request, id):
    clinic = get_object_or_404(Clinic, id=id)
    form = CommentForm(request.POST or None)
    context = {
        'clinic': clinic,
        'form': form,
        'comments': clinic.comments.all()
    }
    return render(request, 'places/profile.html', context)

@login_required
def add_comment(request, clinic_id):
    clinic = get_object_or_404(Clinic, pk=clinic_id)
    form = CommentForm(request.POST or None)
    context = {
        'clinic': clinic,
        'form': form,
        'comments': clinic.comments.all(),
    }
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.clinic = clinic
        comment.save()
        return redirect('places:clinic', id=clinic_id)
    return render(request, 'places/profile.html', context)

vethelp/users/views.py
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm


class SignUp(CreateView):
    form_class = CreationForm
    template_name = 'users/signup.html'
    success_url = reverse_lazy('places:clinics')

vethelp/templates/base.html
{% load static %}
<!DOCTYPE html> 
<html lang="ru">          
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image" href="{% static 'img/fav.ico' %}">
    <meta name="msapplication-TileColor" content="#000">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'css/info_page.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU&amp;apikey=d19fb8ad-ebc6-49ad-9f00-717eb4376883" type="text/javascript"></script>
    <script src="{% static 'js/clinic_map.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/area_map.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/vet_clinics.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/walking_areas.js' %}" type="text/javascript"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <title>{% block title %}VetHelp{% endblock %}</title>
  </head>
  <body>       
    <header>
      {% include 'includes/header.html' %}
    </header>
    <main>
      <div class="container py-5">
        {% block content %}
          Контент не подвезли :(
        {% endblock %}
      </div>
    </main>
    <footer class="border-top text-center py-3">
      {% include 'includes/footer.html' %}
    </footer>
  </body>
</html> 

vethelp/templates/core/403csrf.html
{% extends "base.html" %}
{% block title %}Custom CSRF check error{% endblock %}
{% block content %}
  <h1>Custom CSRF check error. 403</h1>
{% endblock %}

vethelp/templates/includes/footer.html
<p>© 2022 Copyright VetHelp</p>

vethelp/templates/includes/header.html
{% load static %}
{% with request.resolver_match.view_name as view_name %} 
  <nav class="navbar navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{%url 'places:info'%}">
        <img src="{% static 'img/logo.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span>VetHelp</span>
      </a>
      <ul class="nav nav-pills">
        <li class="nav-item custom-item"> 
          <a class="nav-link {% if view_name  == 'places:clinics' %}active{% endif %}" href="{% url 'places:clinics' %}">Ветеринарные учреждения</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if view_name  == 'places:areas' %}active{% endif %}" href="{% url 'places:areas' %}">Площадки для выгула домашних животных</a>
        </li>
        {% if user.is_authenticated %}
          <li class="nav-item">
            <div class="dropdown">
              <button class="btn btn-success dropdown-toggle" type="button" data-toggle="dropdown">
                Пользователь: {{ user.username }}
              </button>
              <ul class="dropdown-menu">
                <li><a class="dropdown-item" href="{% url 'users:password_change' %}">Изменить пароль</a></li>
                <li><a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a></li>
              </ul>
            </div>
          <li>
        {% else %}
          <li class="nav-item"> 
            <a class="nav-link link-light" href="{% url 'users:login' %}">Войти</a>
          </li>
          <li class="nav-item"> 
            <a class="nav-link link-light" href="{% url 'users:signup' %}">Регистрация</a>
          </li>
        {% endif %}
      </ul>
    </div>
  </nav>
{% endwith %}

vethelp/templates/places/area.html
{% extends 'base.html' %}
{% block title %}VetHelp - Площадки для выгула{% endblock %}
{% block content %}
    <div class='map'>
        <div id="area_map"></div>
    </div>
{% endblock %}

vethelp/templates/places/clinic.html
{% extends 'base.html' %}
{% block title %}VetHelp - Ветеринарные учреждения{% endblock %}
{% block content %}
    <div class='map'>
        <div id="clinic_map"></div>
    </div>
    <table class="table">
        <thead>
            <tr>
                <th>Ветеринарные учреждения</th>
            </tr>
        </thead>
        <tbody>
            {% for clinic in clinics %}
                <tr>
                    <td><a href="{% url 'places:clinic' clinic.id %}">{{clinic.title}}</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

vethelp/templates/places/info.html
{% extends 'base.html' %}
{% load static %}
{% block title %}VetHelp{% endblock %}
{% block content %}
    <h1>
        VetHelp - сервис поиска ветеринарных учреждений
    </h1>
    <p>
        Этот сайт был разработан в ходе выполнения курсового проекта. Здесь вы можете узнать о ветеринарных учреждениях в Москве, узнать к ним дорогу, и поделиться своим мнением о конкретной организации. Также вы можете посмотреть на имеющиеся в Москве площадки для выгула домашних животных.
    </p>
{% endblock %}

vethelp/templates/places/profile.html
{% extends 'base.html' %}
{% load user_filters %}
{% block title %}{{clinic.title}}{% endblock %}
{% block content %}
    <h1>
        {{clinic.title}}
    </h1>
    {% if user.is_authenticated %}
        <div class="card my-4">
            <h5 class="card-header">Добавить комментарий:</h5>
            <div class="card-body">
                <form method="post" action="{% url 'places:add_comment' clinic.id %}">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group row my-2 p-2">
                            <label for="{{ field.id_for_label }}">
                            {{ field.label }}
                            {% if field.field.required %}
                                <span class="required text-danger">*</span>
                            {% endif %}
                            </label>    
                            {{ field|addclass:'form-control' }}
                            {% if field.help_text %}
                            <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                                {{ field.help_text|safe }}
                            </small>
                            {% endif %}
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary">Отправить</button>
                </form>
            </div>
        </div>
    {% endif %}
    {% for comment in comments %}
        <div class="media mb-4">
            <div class="media-body">
            <h5 class="mt-0">
                {{ comment.author.username }}
            </h5>
                <p>
                {{ comment.text|safe }}
                </p>
            </div>
        </div>
    {% endfor %}
{% endblock %}
    {% load user_filters %}
{% if user.is_authenticated %}
  <div class="card my-4">
    <h5 class="card-header">Добавить комментарий:</h5>
    <div class="card-body">
      <form method="post" action="{% url 'posts:add_comment' post.id %}">
        {% csrf_token %}      
        {% for field in form %}
          <div class="form-group row my-2 p-2">
            <label for="{{ field.id_for_label }}">
              {{ field.label }}
              {% if field.field.required %}
                <span class="required text-danger">*</span>
              {% endif %}
            </label>    
            {{ field|addclass:'form-control' }}
            {% if field.help_text %}
              <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                {{ field.help_text|safe }}
              </small>
            {% endif %}
          </div>
        {% endfor %}
        <button type="submit" class="btn btn-primary">Отправить</button>
      </form>
    </div>
  </div>
{% endif %}
{% for comment in comments %}
  <div class="media mb-4">
    <div class="media-body">
      <h5 class="mt-0">
        <a href="{% url 'posts:profile' comment.author.username %}">
          {{ comment.author.username }}
        </a>
      </h5>
        <p>
         {{ comment.text|safe }}
        </p>
      </div>
    </div>
{% endfor %}

vethelp/templates/users/includes/card.html
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        {% block card_header %}
          Контент не подвезли :(
        {% endblock %}
      </div>
      <div class="card-body">
        <p>
          {% block card_body %}
            Контент не подвезли :(
          {% endblock %}
        </p>
      </div>
    </div>
  </div>
</div>

vethelp/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Выход
        </div>
        <div class="card-body">
          <p>
            Вы вышли из своей учётной записи. Ждём вас снова!
          </p>
        </div>
      </div>
    </div>
  </div>
{% endblock %} 

vethelp/templates/users/login.html
{% extends "base.html" %}
{% load user_filters %}
{% block title %}Войти{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
            <a href="{% url 'users:password_reset' %}" class="btn btn-link">
              Забыли пароль?
            </a>
          </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

vethelp/templates/users/password_change_done.html
{% extends "base.html" %}
{% block title %}Ваш пароль изменен{% endblock %}
{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Пароль изменён
          </div>
          <div class="card-body"> 
            <p>Пароль изменён успешно</p>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

vethelp/templates/users/password_change_form.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
      <div class="container py-5"> 
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Изменить пароль
              </div>
              <div class="card-body">

                <form method="post" action="{% url 'users:password_change' %}">
                  {% csrf_token %}

                  <div class="form-group row my-3 p-3">
                    <label for="id_old_password">
                      Старый пароль
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="old_password" autofocus class="form-control" required id="id_old_password">
                  </div>

                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password1">
                      Новый пароль
                      <span class="required text-danger">*</span>
                    </label>    

                    <input type="password" name="new_password1" class="form-control" required id="id_new_password1">
                      <small id="id_new_password1-help" class="form-text text-muted">
                        <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                      </small>
                  </div>

                  <div class="form-group row my-3 p-3">
                    <label for="id_new_password2">
                      Подтверждение нового пароля
                      <span class="required text-danger">*</span>
                    </label>    
                    <input type="password" name="new_password2" class="form-control" required id="id_new_password2">
                  </div>

                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      Изменить пароль
                    </button>
                  </div>
                </form>

              </div>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

vethelp/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block title %}Восстановление пароля завершено{% endblock %}
{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Восстановление пароля завершено
          </div>
          <div class="card-body">
            <p>Ваш пароль был сохранен. Используйте его для входа</p>
            <a href="{% url 'users:login' %}">Войти</a>
          </div> 
        </div> 
      </div>
    </div> 
  </div>
{% endblock %}

vethelp/templates/users/password_reset_confirm.html
{% extends "base.html" %}
{% block title %}Восстановление пароля{% endblock %}
{% block content %}
  <div class="container py-5">
    {% if validlink %}
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              Введите новый пароль
            </div>
            <div class="card-body">
              <form method="post">
                {% csrf_token %}
                <div class="form-group row my-3 p-3">
                  <label for="id_new_password1">
                    Новый пароль        
                    <span class="required text-danger">*</span>        
                  </label>    
                  <input type="password" name="new_password1" class="form-control" required id="id_new_password1">      
                  <small id="id_new_password1-help" class="form-text text-muted">
                    <ul><li>Ваш пароль не должен совпадать с вашим именем или другой персональной информацией или быть слишком похожим на неё.</li><li>Ваш пароль должен содержать как минимум 8 символов.</li><li>Ваш пароль не может быть одним из широко распространённых паролей.</li><li>Ваш пароль не может состоять только из цифр.</li></ul>
                  </small>      
                </div>
                <div class="form-group row my-3 p-3">
                  <label for="id_new_password2">
                    Подтверждение нового пароля        
                    <span class="required text-danger">*</span>        
                  </label>    
                  <input type="password" name="new_password2" class="form-control" required id="id_new_password2">      
                </div>
                <div class="col-md-6 offset-md-4">
                  <button type="submit" class="btn btn-primary">
                    Назначить новый пароль
                  </button>
                </div>
              </form>
            </div> <!-- card body -->
          </div> <!-- card -->
        </div> <!-- col -->
      </div> <!-- row -->
    {% else %}
      <div class="row justify-content-center">
        <div class="col-md-8 p-5">
          <div class="card">
            <div class="card-header">
              Ошибка
            </div>
            <div class="card-body">
              <p>Ссылка сброса пароля содержит ошибку или устарела.</p>
            </div> <!-- card body -->
          </div> <!-- card -->
        </div> <!-- col -->
      </div> <!-- row -->
    {% endif %}
  </div>
{% endblock %}

vethelp/templates/users/password_reset_done.html
{% extends "base.html" %}
{% block title %}Восстановление пароля{% endblock %}
{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Отправлено письмо
          </div>
          <div class="card-body">
            <p>Проверьте свою почту, вам должно прийти письмо со ссылкой для восстановления пароля</p>
          </div> 
        </div> 
      </div>
    </div> 
  </div>
{% endblock %}

vethelp/templates/users/password_reset_form.html
{% extends "base.html" %}
{% block title %}Восстановление пароля{% endblock %}
{% block content %}
  <div class="container py-5"> 
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            Чтобы сбросить старый пароль — введите адрес электронной почты, под которым вы регистрировались
          </div>
          <div class="card-body"> 
            <form method="post" action="{% url 'users:password_reset' %}">
              {% csrf_token %}
              <div class="form-group row my-3 p-3">
                <label for="id_email">
                  Адрес электронной почты
                  <span class="required text-danger">*</span>
                </label>    
                <input type="email" name="email" maxlength="254" class="form-control" required id="id_email">
              </div>
              <div class="col-md-6 offset-md-4">
                <button type="submit" class="btn btn-primary">
                  Сбросить пароль
                </button>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>  
  </div>
{% endblock %}

vethelp/templates/users/signup.html
{% extends "base.html" %}
{% block title %}Зарегистрироваться{% endblock %}
{% block content %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card">
        <div class="card-header">
          Зарегистрироваться
        </div>
        <div class="card-body">
          {% load user_filters %}
          {% if form.errors %}
            {% for field in form %}
              {% for error in field.errors %}            
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
              <div class="alert alert-danger">
                {{ error|escape }}
              </div>
            {% endfor %}
          {% endif %}
          <form method="post" action="{% url 'users:signup' %}">
            {% csrf_token %}
            {% for field in form %}
              <div class="form-group row my-3 p-3">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>    
                {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            {% endfor %}
            <div class="col-md-6 offset-md-4">
              <button type="submit" class="btn btn-primary">
                Зарегистрироваться
              </button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}